id: I7E5D4D8D
legacy_id: P009088
ocr_import_info:
  bdrc_scan_id: W29635
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T19:03:12'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T14:09:09.415385+00:00'
last_modified: 2022-09-02 22:09:31.479484
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29635
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29635
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསྟན་རྒྱས་སྨོན་ལམ་རྡོ་རྗེའི་སྒྲ་དབྱངས།
  author: འབྲི་གུང་ཆེ་ཚང ༠༧་བསྟན་འཛིན་འཕྲིན་ལས་ལྷུན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.9717745312283508
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I5539:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5539
      total_pages: 98
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5539.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9717745312283508
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
