id: I7E5D4D8D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:03:50+00:00'
last_modified: '2022-06-08T08:31:58.538600+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29635
  title: བསྟན་རྒྱས་སྨོན་ལམ་རྡོ་རྗེའི་སྒྲ་དབྱངས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5057':
      image_group_id: I5539
      title: ''
      total_pages: 98
      order: 1
      base_file: 5057.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
